### ISSUE TITLE
Polish docs & Dockerfile

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#10]
Before submit we should polish documents and build dockerfile.

I make template of [dockerfile](https://github.com/KAIST-IS521/2018s-onion-team4/tree/proto/Docker/dockerfile).

You may improve from that file.

You should notice that

- Dockerfile can automatically fetch the latest version of your onion messenger, compile it, and run it. 
- Dockerfile would also have to transfer the user's private key into the docker container.
- Assume that the user's private key file exists in the same directory with the Dockerfile.

Todo
-----
- [x] Make dockerfile
- [x] Polishing docs

**Comment by saykim0727** [comment]
i made the dockerfile with shell script.
is it finish? or should i update some code?

**Comment by hestati63** [comment]
If dockerfile is work well, you don't have anything to do related to docker file.

This issue also related to `Polish docs(ie. Polishing README.md, ...)`.

**Comment by hestati63** [comment]
@thefffrla @khsdo95 
Can you guys help to build dockerfile?

**Comment by khsdo95** [comment]
Now, `dockerfile` works well~
sorry for some mistakes.

**Comment by hestati63** [comment]
@saykim0727 Can you add pictures of our messenger's UI to README.md?

- Login UI
- Chat UI
- Chat UI with Asciiart feature.

**Comment by saykim0727** [comment]
Sure, i can
