### ISSUE TITLE
Gitpitch

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#12]
We should make gitpitch slide before due date.

The aim of presentation is `sell our product`

**Comment by khsdo95** [comment]
Do we need to create PITCHME.md in this repo?
or in '2018s-presentation-team4' ?

**Comment by hestati63** [comment]
We should create it in 2018s-presentation-team4 repo.

**Comment by hestati63** [comment]
Consider #15 before making presentation.

**Comment by hestati63** [comment]
I make architecture section.

You may check it 2018s-presentation-team4's onion branch.

**Comment by saykim0727** [comment]
I make feature section, too.
