### ISSUE TITLE
About passinfo

### ISSUE THREAD

**Issue by khsdo95** [KAIST-IS521/2018s-onion-team4#17]
There is a variable in PGP, named passinfo
However, I can't understand what it is. It is not finger print, user id, and short uid
It comes from passphrase callback but we will not use GPGME. Then I don't know how to get the information

Can I remove this?

Below comes from GPGME Manual
> The argument passphrase info, if not NULL, will give further information about the
> context in which the passphrase is required. This information is engine and operation
> specific.

**Comment by hestati63** [comment]
Passinfo has a string of `PGP key id (Eg. 123456A)`.

**Comment by khsdo95** [comment]
![image](https://user-images.githubusercontent.com/9199607/38011737-96db1d1a-3299-11e8-9605-5a0fdb38c977.png)

Is this `PGP key id `?
![image](https://user-images.githubusercontent.com/9199607/38011751-a41d23ce-3299-11e8-90b4-09d71623fb9a.png)

I think they are different.

**Comment by khsdo95** [comment]
I think I can set passinfo to `PGP key id`. Thanks.
