### ISSUE TITLE
Design choice about onion routing

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#18]
There is one design choice about onion routing.

Does client need to add itself to onion layer?

let's discuss.

**Comment by khsdo95** [comment]
Is there any benefits when a client route packet to itself?

I think it is meaningless on both parts, security and efficiency.
I think increasing one candidate to route doesn't have big effect on anonymity
and efficiency is straightforward.

Is there something i missed?

**Comment by saykim0727** [comment]
i agree with @khsdo95 
i think there is no reason to do so.

**Comment by hestati63** [comment]
Okay.

Then there should be no onion layer that hop to itself.

Does you guys have any comment about it?

**Comment by sangkilc** [comment]
Good to see some discussion going on here.

**Comment by hestati63** [comment]
We select below design choices.
- No hop to itself.
- Client does not add itself to onion layer.

**Comment by khsdo95** [comment]
Also all nodes doesn't route packet to itself. :)
9899da1f199e26f4ca0ef32ff959c983bbbcce2f
