### ISSUE TITLE
Discussion about our system.

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#19]
We should discuss about below things.

- What's the name of our messenger?
- What is strong point?
- Anything else?

Discuss those things at here.

**Comment by hestati63** [comment]
This is our system's strong points.

- Distribute System: No single point of failure.
- IO multiplexing with select: Can handle lots of clients. Also efficient!

**Comment by saykim0727** [comment]
Our program can send images with url as Asciiart.
I think it is very strong point.

**Comment by saykim0727** [comment]
How about user interface?
I think ui is nice!

**Comment by thefffrla** [comment]
As for the name, how about VOM?
1. Simple as VIM's Onion Messenger,
2. Has similar name as our team name, ( easy to show we made it )
3. Can make catchphrase, 'VIM VOM', as in 'Ding dong'
just for saying

**Comment by khsdo95** [comment]
VOM is nice!

Our ui can be selected by user, TUI and CUI.
I think it also can be strong point.
