### ISSUE TITLE
Select which library to use for PGP encrypt and decrypt

### ISSUE THREAD

**Issue by khsdo95** [KAIST-IS521/2018s-onion-team4#2]
Until 3/21 10:00

**Comment by khsdo95** [comment]
GPGME
https://gnupg.org/software/gpgme/index.html

Manual : https://www.gnupg.org/documentation/manuals/gpgme/

sudo apt-get install libgpgme11-dev

**Comment by hestati63** [comment]
This is too slow to use for onion routing.

We should change it.

**Comment by khsdo95** [comment]
Yes. I am going to change it.
There is other way that popen and get output from it

**Comment by hestati63** [comment]
#17

**Comment by khsdo95** [comment]
848ec20ee3120511c3d93bc44ea2d5aea35bbe90

popen looks like very very faster than GPGME
