### ISSUE TITLE
Polish UI

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#20]
We should polish UI.

- [x] Implement UIProvider::PushChat(string user, string text);
- [ ] For CUI, handle case that message comes in during writing message.

**Comment by thefffrla** [comment]
For UIProvider::PushChat(string user, string text),
I assume 'string user' is the sender of the 'string text'?

**Comment by hestati63** [comment]
Sure.

**Comment by khsdo95** [comment]
Sorry, I read this issue now.
I implemented PushChat already.
Not only Push Chat, PushNotification and PushError are implemented

srr..
