### ISSUE TITLE
Logout or Disconnected

### ISSUE THREAD

**Issue by khsdo95** [KAIST-IS521/2018s-onion-team4#26]
We should deal with disconnect.

I think there are 2 ways.
1. When a node is disconnected, it sends `Disconnect` packet to other nodes
2. When a node needs to update table (e.g. send packet), check all connections and update table locally.

**Comment by hestati63** [comment]
Select can detect disconnection.
Fd is not writable means that client is disconnected.

**Comment by hestati63** [comment]
Also, there is assumption in this project.

In activity documentation: `For simplicity, we assume that the list always contains the correct information: every client in the list should be up and reachable, and we do not consider any spoofing attack on this list.`.

**Comment by khsdo95** [comment]
Then, don't we need to implement `cleanup_users` which checks that fds are available and remove if it is not available?
I think our code can add user of not available fd to onion layer

**Comment by hestati63** [comment]
By the assumption, those case doesn’t exists.

However, we can implement them!
