### ISSUE TITLE
Avoid race

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#27]
Since our program use multiple threads, we should avoid race condition.

We have two choices to avoid race.

1. Add lock to all shared variable.

2. Use only 2 threads: Now our system now uses `popen` to handle PGP enc & dec. We can change those codes to use IO multiplexing.

Which one do you prefer?

**Comment by thefffrla** [comment]
I don't know much about this, but it sounds like the second option is much easier to manage.
If someone generous enough to write some pros and cons, it would really be helpful to make the decision.
