### ISSUE TITLE
Create dummy PGP key

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#29]
We should create 5 docker containers.

Therefore, we should create 5 dummy PGP keys.

**Comment by saykim0727** [comment]
Ok , i will upload 5 dummy PGP keys in Docker directory.

**Comment by saykim0727** [comment]
passphrase = dummy+[num]
ex) dummy1 PGP key passphrase is "dummy1"

**Comment by hestati63** [comment]
Thanks.
