### ISSUE TITLE
Build UI

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#3]
We will support two type of ui.

- [x] Text-based User Interface using ncurse.
- [x] Commandline-based User Interface.

**Comment by hestati63** [comment]
Can someone make commandline based user interface?

Implement `Commandline-based User Interface`  = Implement `CUI::CUIProvider`

**Comment by hestati63** [comment]
I think @thefffrla can help this.

**Comment by thefffrla** [comment]
Got the gist of the functions pre-defined, but having a hard time understanding the parameters.

Would be very helpful if there are some explanations about them, i.e uid, info in GetUserInfo and so on.

**Comment by hestati63** [comment]
Can you list all parameters that you can not understand here?

**Comment by thefffrla** [comment]
@hestati63 
Brief explanations about those parameters in GetUserInfo & UserInputLoop would really save me.

**Comment by hestati63** [comment]
`pair<string, string> GetUserInfo(string uid, string info, char *msg);`
`@uid`:      PGP user id information (Eg. "Minkyu Jung <hestati@kaist.ac.kr>")
`@info`:     PGP key id (Eg. 123456A)
`@msg`:    Additional msg to display
`@return`:  pair<string, string>(githubID, passphrase)

`void UserInputLoop(string uid, string info, void (*handler)(char *, void *), void *aux);`
`@uid`:      PGP user id information (Eg. "someone \<someone@example.com\>")
`@info`:     PGP key id (Eg. 123456A)
`@handler`: Function that execute when user input provided.
See https://github.com/KAIST-IS521/2018s-onion-team4/blob/proto/src/OnionMessenger.cc#L43 and
https://github.com/KAIST-IS521/2018s-onion-team4/blob/proto/src/OnionMessenger.cc#L219 for details.
`@aux`: auxiliary value which is passed to second argument of handler.

**Comment by hestati63** [comment]
@saykim0727 Can you help this?
