### ISSUE TITLE
question about getting user list

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-onion-team4#33]
Why i can't get other client's list?
What should i do more?
![peek 2018-04-10 09-07](https://user-images.githubusercontent.com/36834930/38529257-b6e42e62-3c9e-11e8-93fe-243ef29e928f.gif)

**Comment by khsdo95** [comment]
Because of our design choice, distributed, we need to know at least a ip address of a node in network.
You can start with Onionmessenger with
-n [ip address][|:port]

Sorry for your inconvenience.
Thanks.
