### ISSUE TITLE
Update protocol

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#5]
Since we misunderstood protocol, we should update our protocol.

**Comment by hestati63** [comment]
Since
- We do not need to relay packets to all client in the network.
- Our design choice is distribute system.

We don't need to adopt onion routing.

Just pass message end-to-end.

**Comment by mikkang** [comment]
Think again about the meaning of onion routing.

You have to notice following sentence in specification.

> **Other clients** cannot see its content or figure out who is sending the message to whom.

not just a center main server
