### ISSUE TITLE
Implement protocol

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#7]
Implement protocol before 2018-03-21 23:59.

**Comment by hestati63** [comment]
We need to add one more protocol for #8.

Can you design and implement protocol for that?

@thefffrla

**Comment by thefffrla** [comment]
Check update on the branch 'packet'. Img packet is designed similar to the Msg packet. Please verify.

**Comment by hestati63** [comment]
@thefffrla 

Packet branch cannot merge-able with proto branch.
Please solve this merge conflict.

**Comment by thefffrla** [comment]
Should be merge-able @hestati63.

**Comment by hestati63** [comment]
Use PacketBuilder for serialize. Also return type of serialize should be pair<char *, int>
Change [img::Serialize](https://github.com/KAIST-IS521/2018s-onion-team4/blob/84095d1d6c43c1cfd0a925bff4023391cf9935cb/src/Packet.cc#L226) like [Handshake::Serialize](
https://github.com/KAIST-IS521/2018s-onion-team4/blob/84095d1d6c43c1cfd0a925bff4023391cf9935cb/src/Packet.cc#L132).
@thefffrla
